Install PangoFc and PangoOT GObject-Introspection
If we don't install these, we can't load PangoXft and PangoFT2, which
depend on them:

    $ GI_TYPELIB_PATH=${DESTDIR}/usr/lib/x86_64-linux-gnu/girepository-1.0 python3
    ...
    >>> from gi.repository import PangoXft
    ...
    gi.RepositoryError: Typelib file for namespace 'PangoOT', version '1.0' not found

Signed-off-by: Simon McVittie <smcv@debian.org>